feat (profile): added feature flag for new profile screen design
hevelius/io-app pull request #1
Opened 2022-05-30 13:24 UTC by hevelius

## Short description
This PR adds a feature flag for the new profile screen design.

## List of changes proposed in this pull request
- Added FF in .env for local and prod
- Added FF in config.ts

## How to test
enabled feature flag NEW_PROFILE_SCREEN_ENABLED in .env file

2022-05-31 10:23 UTC, debiff requested changes

2022-05-31 10:23 UTC, debiff commented on ios/Podfile.lock
> +  trunk:
Why do you need to push the new Podfile?

2022-05-31 14:14 UTC, hevelius commented on ios/Podfile.lock
> +  trunk:
Thanks for the question @debiff . This happened because the reference to the master repo was lost. I added it manually and the Podfile.lock now is aligned. I come back to you soon with a revert.

https://github.com/CocoaPods/CocoaPods/issues/9190#issuecomment-645082600

2022-06-06 11:39 UTC, debiff approved these changes

2022-06-06 11:40 UTC, merged